
  create table "public"."cabins" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "maxCapacity" smallint,
    "regularPrice" smallint,
    "discount" smallint,
    "description" text,
    "image" text
      );


alter table "public"."cabins" enable row level security;


  create table "public"."guests" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "fullName" text,
    "email" text,
    "nationalID" text,
    "nationality" text,
    "countryFlag" text
      );


alter table "public"."guests" enable row level security;


  create table "public"."settings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "minBookingLength" smallint,
    "maxBookingLength" smallint,
    "maxGuestsPerBooking" smallint,
    "breakfastPrice" real
      );


alter table "public"."settings" enable row level security;

CREATE UNIQUE INDEX cabins_pkey ON public.cabins USING btree (id);

CREATE UNIQUE INDEX guests_pkey ON public.guests USING btree (id);

CREATE UNIQUE INDEX settings_pkey ON public.settings USING btree (id);

alter table "public"."cabins" add constraint "cabins_pkey" PRIMARY KEY using index "cabins_pkey";

alter table "public"."guests" add constraint "guests_pkey" PRIMARY KEY using index "guests_pkey";

alter table "public"."settings" add constraint "settings_pkey" PRIMARY KEY using index "settings_pkey";

grant delete on table "public"."cabins" to "anon";

grant insert on table "public"."cabins" to "anon";

grant references on table "public"."cabins" to "anon";

grant select on table "public"."cabins" to "anon";

grant trigger on table "public"."cabins" to "anon";

grant truncate on table "public"."cabins" to "anon";

grant update on table "public"."cabins" to "anon";

grant delete on table "public"."cabins" to "authenticated";

grant insert on table "public"."cabins" to "authenticated";

grant references on table "public"."cabins" to "authenticated";

grant select on table "public"."cabins" to "authenticated";

grant trigger on table "public"."cabins" to "authenticated";

grant truncate on table "public"."cabins" to "authenticated";

grant update on table "public"."cabins" to "authenticated";

grant delete on table "public"."cabins" to "postgres";

grant insert on table "public"."cabins" to "postgres";

grant references on table "public"."cabins" to "postgres";

grant select on table "public"."cabins" to "postgres";

grant trigger on table "public"."cabins" to "postgres";

grant truncate on table "public"."cabins" to "postgres";

grant update on table "public"."cabins" to "postgres";

grant delete on table "public"."cabins" to "service_role";

grant insert on table "public"."cabins" to "service_role";

grant references on table "public"."cabins" to "service_role";

grant select on table "public"."cabins" to "service_role";

grant trigger on table "public"."cabins" to "service_role";

grant truncate on table "public"."cabins" to "service_role";

grant update on table "public"."cabins" to "service_role";

grant delete on table "public"."guests" to "anon";

grant insert on table "public"."guests" to "anon";

grant references on table "public"."guests" to "anon";

grant select on table "public"."guests" to "anon";

grant trigger on table "public"."guests" to "anon";

grant truncate on table "public"."guests" to "anon";

grant update on table "public"."guests" to "anon";

grant delete on table "public"."guests" to "authenticated";

grant insert on table "public"."guests" to "authenticated";

grant references on table "public"."guests" to "authenticated";

grant select on table "public"."guests" to "authenticated";

grant trigger on table "public"."guests" to "authenticated";

grant truncate on table "public"."guests" to "authenticated";

grant update on table "public"."guests" to "authenticated";

grant delete on table "public"."guests" to "postgres";

grant insert on table "public"."guests" to "postgres";

grant references on table "public"."guests" to "postgres";

grant select on table "public"."guests" to "postgres";

grant trigger on table "public"."guests" to "postgres";

grant truncate on table "public"."guests" to "postgres";

grant update on table "public"."guests" to "postgres";

grant delete on table "public"."guests" to "service_role";

grant insert on table "public"."guests" to "service_role";

grant references on table "public"."guests" to "service_role";

grant select on table "public"."guests" to "service_role";

grant trigger on table "public"."guests" to "service_role";

grant truncate on table "public"."guests" to "service_role";

grant update on table "public"."guests" to "service_role";

grant delete on table "public"."settings" to "anon";

grant insert on table "public"."settings" to "anon";

grant references on table "public"."settings" to "anon";

grant select on table "public"."settings" to "anon";

grant trigger on table "public"."settings" to "anon";

grant truncate on table "public"."settings" to "anon";

grant update on table "public"."settings" to "anon";

grant delete on table "public"."settings" to "authenticated";

grant insert on table "public"."settings" to "authenticated";

grant references on table "public"."settings" to "authenticated";

grant select on table "public"."settings" to "authenticated";

grant trigger on table "public"."settings" to "authenticated";

grant truncate on table "public"."settings" to "authenticated";

grant update on table "public"."settings" to "authenticated";

grant delete on table "public"."settings" to "postgres";

grant insert on table "public"."settings" to "postgres";

grant references on table "public"."settings" to "postgres";

grant select on table "public"."settings" to "postgres";

grant trigger on table "public"."settings" to "postgres";

grant truncate on table "public"."settings" to "postgres";

grant update on table "public"."settings" to "postgres";

grant delete on table "public"."settings" to "service_role";

grant insert on table "public"."settings" to "service_role";

grant references on table "public"."settings" to "service_role";

grant select on table "public"."settings" to "service_role";

grant trigger on table "public"."settings" to "service_role";

grant truncate on table "public"."settings" to "service_role";

grant update on table "public"."settings" to "service_role";


