
  create table "public"."bookings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "startDate" timestamp without time zone,
    "endDate" timestamp without time zone,
    "numNights" smallint,
    "numGuests" smallint,
    "cabinPrice" real,
    "extrasPrice" real,
    "totalPrice" real,
    "status" text,
    "hasBreakfast" boolean,
    "isPaid" boolean,
    "observations" text,
    "cabinID" bigint,
    "guestID" bigint
      );


alter table "public"."bookings" enable row level security;

CREATE UNIQUE INDEX bookings_pkey ON public.bookings USING btree (id);

alter table "public"."bookings" add constraint "bookings_pkey" PRIMARY KEY using index "bookings_pkey";

alter table "public"."bookings" add constraint "bookings_cabinID_fkey" FOREIGN KEY ("cabinID") REFERENCES public.cabins(id) not valid;

alter table "public"."bookings" validate constraint "bookings_cabinID_fkey";

alter table "public"."bookings" add constraint "bookings_guestID_fkey" FOREIGN KEY ("guestID") REFERENCES public.guests(id) not valid;

alter table "public"."bookings" validate constraint "bookings_guestID_fkey";

grant delete on table "public"."bookings" to "anon";

grant insert on table "public"."bookings" to "anon";

grant references on table "public"."bookings" to "anon";

grant select on table "public"."bookings" to "anon";

grant trigger on table "public"."bookings" to "anon";

grant truncate on table "public"."bookings" to "anon";

grant update on table "public"."bookings" to "anon";

grant delete on table "public"."bookings" to "authenticated";

grant insert on table "public"."bookings" to "authenticated";

grant references on table "public"."bookings" to "authenticated";

grant select on table "public"."bookings" to "authenticated";

grant trigger on table "public"."bookings" to "authenticated";

grant truncate on table "public"."bookings" to "authenticated";

grant update on table "public"."bookings" to "authenticated";

grant delete on table "public"."bookings" to "postgres";

grant insert on table "public"."bookings" to "postgres";

grant references on table "public"."bookings" to "postgres";

grant select on table "public"."bookings" to "postgres";

grant trigger on table "public"."bookings" to "postgres";

grant truncate on table "public"."bookings" to "postgres";

grant update on table "public"."bookings" to "postgres";

grant delete on table "public"."bookings" to "service_role";

grant insert on table "public"."bookings" to "service_role";

grant references on table "public"."bookings" to "service_role";

grant select on table "public"."bookings" to "service_role";

grant trigger on table "public"."bookings" to "service_role";

grant truncate on table "public"."bookings" to "service_role";

grant update on table "public"."bookings" to "service_role";

grant delete on table "public"."cabins" to "postgres";

grant insert on table "public"."cabins" to "postgres";

grant references on table "public"."cabins" to "postgres";

grant select on table "public"."cabins" to "postgres";

grant trigger on table "public"."cabins" to "postgres";

grant truncate on table "public"."cabins" to "postgres";

grant update on table "public"."cabins" to "postgres";

grant delete on table "public"."guests" to "postgres";

grant insert on table "public"."guests" to "postgres";

grant references on table "public"."guests" to "postgres";

grant select on table "public"."guests" to "postgres";

grant trigger on table "public"."guests" to "postgres";

grant truncate on table "public"."guests" to "postgres";

grant update on table "public"."guests" to "postgres";

grant delete on table "public"."settings" to "postgres";

grant insert on table "public"."settings" to "postgres";

grant references on table "public"."settings" to "postgres";

grant select on table "public"."settings" to "postgres";

grant trigger on table "public"."settings" to "postgres";

grant truncate on table "public"."settings" to "postgres";

grant update on table "public"."settings" to "postgres";


